### PR TITLE
Update USB libs from wixel-SDK.

### LINKED ISSUE #52: Compile Issue
I'm getting compiler errors when using the makefile on Ubuntu 16.04 LTS.
The code is the latest from the master branch as of February 12, 2017.

make error:
```
Compiling libraries/src/usb/usb.rel
libraries/src/usb/usb.c:292: error 146: two or more storage classes in declaration for 'usbStandardDeviceRequestHandler'
Makefile:172: recipe for target 'libraries/src/usb/usb.rel' failed
make: *** [libraries/src/usb/usb.rel] Error 1
```

SDCC -v output (in case it's useful):
```
SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ds390/TININative/ds400/hc08/s08/stm8 3.5.0 #9253 (Mar 24 2016) (Linux)
published under GNU General Public License (GPL)
```

### PR DESCRIPTION
**Pull request by jareware**
This fixes a compilation issue on a more recent SDCC (3.5.0), that ships with latest stable Raspbian, for example.

From: https://github.com/pololu/wixel-sdk/tree/513d976863a7be68cce523422735dd4a98a3435e

Closes: https://github.com/StephenBlackWasAlreadyTaken/wixel-xDrip/issues/52

### CODE REVIEW

**Comment by jareware** [comment]
Note that I also tried to update the [rest of the wixel-sdk libs](https://github.com/pololu/wixel-sdk/tree/513d976863a7be68cce523422735dd4a98a3435e/libraries) in the same go, but got:

```
Linking apps/dexdrip/dexdrip.hex

?ASlink-Warning-Undefined Global '_radioMacResume' referenced by module 'dexdrip'

?ASlink-Warning-Undefined Global '_radioMacSleep' referenced by module 'dexdrip'
apps.mk:32: recipe for target 'apps/dexdrip/dexdrip.hex' failed
make: *** [apps/dexdrip/dexdrip.hex] Error 1
Firmware failed to build :(
```

Seeing as the `usb.c` patch worked, I decided to leave this PR at that.

**Comment by jamorham** [comment]
Thanks for the minimal changes in this patch. Often better that way I think.

Can you confirm that after applying this patch you are able to compile a .wxl file which then works correctly in USB mode? I appreciate that this patch fixed the compile problem but I am interested in the end-to-end test once that patch is applied.

**Comment by jamorham** [comment]
This also compiles successfully on SDCC 3.4.0

**Comment by jareware** [comment]
Yes, I ran `forusb.sh` from start to finish with this patch, and ended up looking at successfully incoming `Serial line: ...` messages on the console. 👍

**Comment by jamorham** [comment]
Thanks!

**Pull request merged**
